name: Dead domain cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  cleanup:
    name: Cleanup dead domains 🧹
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: ".nvmrc"

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run cleanup
        uses: npm run dead-domains:fix

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "::set-output name=changes::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes::true"
          fi

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -m "fix: remove dead domains"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: steps.git-check.outputs.changes == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fix dead domains"
          title: "Automated dead domains cleanup"
          body: "This is an auto-generated PR with fixes for dead domains."
          branch: "cleanup/dead-domains"
