name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Validate codeowners
        run: npm run codeowners:check

      - name: Build filters
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out/
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: deploy

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Checkout the deploy branch
          git fetch origin deploy:deploy
          git checkout deploy

          # Remove old files
          git rm -r *

          # Copy new files from out to root directory
          cp -r out/* .

          # Add all files to staging
          git add .

          # Commit and push changes
          git commit -m "Deploying to deploy branch"
          git push origin HEAD:deploy --force
