name: Test & Deploy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: corepack enable
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Setup Biome
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5 # v2

      - name: Run filters lint
        run: pnpm run lint:filters

      - name: Run Biome
        run: biome ci . --reporter=github

      - name: Validate codeowners
        run: pnpm run codeowners:check

      - name: Build filters
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        with:
          name: out
          path: out/
  deploy:
    name: Deploy 🚀
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: >
      (
        github.ref == 'refs/heads/main' &&
        contains(github.event.head_commit.modified, 'filters/') &&
        github.event_name == 'push'
      ) || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: deploy

      - name: Download Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: out
          path: out

      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2 # v4
        with:
          folder: out
          branch: deploy
          clean: true
