name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Setup Biome
        uses: biomejs/setup-biome@c016c38f26f2c4a6eb3662679143614a254263fd # v2

      - name: Run filters lint
        run: pnpm run lint:filters

      - name: Run Biome
        run: biome ci . --reporter=github

      - name: Validate codeowners
        run: pnpm run codeowners:check

      - name: Build filters
        run: pnpm run build

  attempt_deploy:
    name: Attempt deploy 🔭
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      previous_sha: ${{ github.event.before }}
      current_sha: ${{ github.sha }}
