name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - run: corepack enable
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Setup Biome
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5 # v2

      - name: Run filters lint
        run: pnpm run lint:filters

      - name: Run Biome
        run: biome ci . --reporter=github

      - name: Validate codeowners
        run: pnpm run codeowners:check

      - name: Build filters
        run: pnpm run build

  attempt_deploy:
    name: Attempt deploy 🔭
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      previous_sha: ${{ github.event.before }}
      current_sha: ${{ github.sha }}